### ISSUE TITLE
Resolve Merge Conflicts

### ISSUE THREAD

**Issue by philippabele** [philippabele/pythonic-api-design#26]
I accepted your 3 PRs

- https://github.com/philippabele/pythonic-api-design/pull/22
- https://github.com/philippabele/pythonic-api-design/pull/24
- https://github.com/philippabele/pythonic-api-design/pull/23

There are now some merge conflicts. Please take care of them and resolve the conflicts.

**Comment by HenrikFrtz** [comment]
I resolved all merge conflicts 👍🏻
