### ISSUE TITLE
Split up Readme

### ISSUE THREAD

**Issue by philippabele** [philippabele/pythonic-api-design#27]
Split up your Readme

Your (main) readme.md file in ./readme.md should only contain a table of content

Please provide detailed information in the corresponding sub folder of your example.

A possible path to a detailed readme for the elastic example could look like this
- [pythonic-api-design](https://github.com/philippabele/pythonic-api-design/tree/development)/02_simple_elastic_logging/readme.md

**Comment by HenrikFrtz** [comment]
@philippabele 

I've split them all up and linked them below "Documentation".

I also converted the badges from HTML to Markdown. Opening a new tab is not possible now, but I've read about XSS in the past on GitHub if target="_blank" is used.
