### ISSUE TITLE
Use virtual environments and create a requirements.txt file

### ISSUE THREAD

**Issue by philippabele** [philippabele/pythonic-api-design#3]
This [blog post](https://boscacci.medium.com/why-and-how-to-make-a-requirements-txt-f329c685181e) helps to understand and use the concept of virtual environments and requirements.txt files.

**Comment by HenrikFrtz** [comment]
Should pytest be included in requirements.txt?

**Comment by philippabele** [comment]
For the first releases of this project one requirements file for all purpose fits our needs.

**Comment by HenrikFrtz** [comment]
Great, alright!
