### ISSUE TITLE
Remove Elastic Content from CRUD example

### ISSUE THREAD

**Issue by philippabele** [philippabele/pythonic-api-design#36]
https://github.com/philippabele/pythonic-api-design/blob/b40a9b15b16a74bf91cbb164d3a2c6b214b4c5fe/01_simple_crud_sql/src/app/elasticsearch.py#L15

**Comment by HenrikFrtz** [comment]
@philippabele 
Ah, I see. Slowly I understand the structure :)
So I shall create a new API with FastAPI in the elasticsearch subdirectory, so every feature/example can be executed seperately?

**Comment by HenrikFrtz** [comment]
I restructured the project in the [feature/split-up-DockerCompose-file](https://github.com/philippabele/pythonic-api-design/tree/feature/split-up-DockerCompose-file) branch and implemented this issue there all in one go.
