### ISSUE TITLE
Add Comments and Remove Prometheus Content from CRUD

### ISSUE THREAD

**Issue by philippabele** [philippabele/pythonic-api-design#37]
Good examples containt lots of comments.

Please comment your code to make it comprehensible

`# Describe with simple words your code`

https://github.com/philippabele/pythonic-api-design/blob/b40a9b15b16a74bf91cbb164d3a2c6b214b4c5fe/01_simple_crud_sql/src/app/main.py#L10

**Comment by HenrikFrtz** [comment]
Feature branch: [add-comments](https://github.com/philippabele/pythonic-api-design/tree/feature/add-comments)

Ok?
