### ISSUE TITLE
Expand CRUD example to become a pet store

### ISSUE THREAD

**Issue by philippabele** [philippabele/pythonic-api-design#44]
The classic example for a REST api is a pet store.

Expand your example to become a pet store like this https://petstore.swagger.io/#/ on. But focus on CRUD functions for pets. Ignore store and user routes like on the mentioned swagger.io site.

**Comment by HenrikFrtz** [comment]
@philippabele should I expand my simple_crud_sql example OR create a new example '04_petstore_crud'?

**Comment by HenrikFrtz** [comment]
Is it necessary to be able to store a picture of the pet?

**Comment by philippabele** [comment]
> @philippabele should I expand my simple_crud_sql example OR create a new example '04_petstore_crud'?

expand existing one

**Comment by philippabele** [comment]
> Is it necessary to be able to store a picture of the pet?

no. storing pictures is not mandatory.

**Comment by HenrikFrtz** [comment]
@philippabele 
I am struggeling with pytests. 
The first problems in pytest are related to not running database - I have absolutely no idea why it is running in some tests and not in other tests. But the error is reproducible every time. 
Secondly, the "DELETE" tests are not running as expected - http response code is 307. I did not found any regarding issue on the internet... Maybe you have a good tip how to solve this.

![grafik](https://user-images.githubusercontent.com/72461944/174287836-e9becf9f-7613-4191-82f3-5f56ca56caf3.png)
