### ISSUE TITLE
Add new example for async 

### ISSUE THREAD

**Issue by philippabele** [philippabele/pythonic-api-design#45]
One of the main advantages of fastAPI is its capabilties of running concurrent code.

Mention in your example.md a good source for further reading, like this https://christophergs.com/tutorials/ultimate-fastapi-tutorial-pt-9-asynchronous-performance-basics/ on.

**Comment by HenrikFrtz** [comment]
Would you prefer to create a new MD file ("011_fast_api.md") oder to add a section in this [one](https://github.com/philippabele/pythonic-api-design/blob/development/01_simple_crud_sql/01_crud-sql.MD)?

**Comment by philippabele** [comment]
new detailed example -> new md file
