### ISSUE TITLE
Perform a literature review and create list with interesting books

### ISSUE THREAD

**Issue by philippabele** [philippabele/pythonic-api-design#6]
Get access to the [eBook library](https://ebookcentral.proquest.com/auth/lib/mosbach-dhbw/) and create a Markdown file with a list of interesting books.

**Comment by HenrikFrtz** [comment]
@philippabele should the list contain interesting books or books specific to the topic "FastAPI"(Or Microservice architecture)

**Comment by philippabele** [comment]
@HenrikFrtz 

--> books specific to the topic "FastAPI"(Or Microservice architecture)
