### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by philippabele** [philippabele/pythonic-api-design#9]
https://towardsdatascience.com/getting-started-with-elasticsearch-in-python-c3598e718380

**Comment by HenrikFrtz** [comment]
- What does ElasticSearch has to do with logging?
- Should I install Elasticsearch in a Docker Container or locally on my device?
- Do I have to write Logs in a ES DB?

@philippabele

**Comment by philippabele** [comment]
@HenrikFrtz 

- What does ElasticSearch has to do with logging?

https://www.elastic.co/de/log-monitoring

- Should I install Elasticsearch in a Docker Container or locally on my device?

I prefer to run elastic in docker.

- Do I have to write Logs in a ES DB?

Yes.

**Comment by HenrikFrtz** [comment]
@philippabele I'd appreciate if you could answer the questions above to be able to work on this work item :)

**Comment by philippabele** [comment]
-> What exactely should be logged?

The content to be logged does not matter. Its just for demonstrations purpose. For example, set up a GET Route and log the times of the call and the name of the route. Keep it as simple as possible.

-> Should i use the Elastic REST API and requests lib or the elasticsearch lib?

That is part of your student research project. Evaluate possible ways for transfering logs from the api to elasticsearch, describe them and descide on your own which lib to use.

-> Should I implement Kibana as well?

For sure. Its a very nice way to make your logs visible!

**Comment by HenrikFrtz** [comment]
Merged into development
